# Generated by Django 2.2.4 on 2019-09-26 05:32

from django.db import migrations
import fontawesome_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20190925_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='github_url',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='linked_in_url',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='twitter_url',
        ),
        migrations.AddField(
            model_name='profile',
            name='github',
            field=fontawesome_5.fields.IconField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='profile',
            name='linkedin',
            field=fontawesome_5.fields.IconField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='profile',
            name='twitter',
            field=fontawesome_5.fields.IconField(blank=True, max_length=60),
        ),
    ]
