# Generated by Django 2.2.4 on 2019-09-26 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20190926_0532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='github',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='linkedin',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='twitter',
            field=models.URLField(),
        ),
    ]
