# Generated by Django 2.2.4 on 2019-09-27 15:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_auto_20190927_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menu',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
