# Generated by Django 2.2.4 on 2019-09-28 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_skillcategory_technology'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='technology',
            options={'ordering': ('id',), 'verbose_name_plural': 'Technologies'},
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(default='', upload_to='covers/'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(default='', upload_to='screenshots/'),
        ),
        migrations.AlterField(
            model_name='projecttech',
            name='image',
            field=models.ImageField(default='', upload_to='tech/'),
        ),
        migrations.AlterField(
            model_name='technology',
            name='icon',
            field=models.ImageField(default='', upload_to='technology/'),
        ),
    ]
