# Generated by Django 2.2.4 on 2019-10-01 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_auto_20190928_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='handshake',
            field=models.ImageField(default='', upload_to='profile/'),
        ),
    ]
